### ISSUE TITLE
Is this a mistake?  In code file "8_processing.ipynb"

### ISSUE THREAD

**Issue by zhangjiekui** [USC-Melady/Benchmarking_DL_MIMICIII#1]
In code file 8_processing.ipynb

_adm = np.load('res/admission_ids.npy').tolist()
admission_ids = _adm['admission_ids']
admission_ids_txt = _adm['admission_ids_txt']

_adm_first = np.load('res/admission_first_ids.npy').tolist()
admission_first_ids = _adm['admission_ids']  # I think this should be  **_adm_first ['admission_ids']**

**Comment by mengcz13** [comment]
That should be my typo. Sorry for that!

However, **this variable is not used in 8_processing.ipynb and you can just remove it**. Here we simply extract information for each id in case we might need it later. We select first admission_ids in 9_getValidDataset.ipynb.

Also, the last part of 8_processing.ipynb should also be deleted. We only use the folder "admdata_valid" instead of "admdata_first" for later scripts.

Thank you for your correction! I'll fix it after submitting my undergraduate thesis this weekend...

**Comment by zhangjiekui** [comment]
Thanks!
Do you mean these code lines should be deleted?

# def copy_first_admissions(aid):
#     if aid in admission_first_ids_set:
#         res = np.load(os.path.join('admdata', 'adm-%.6d.npy' % aid))
#         np.save(os.path.join('admdata_first', 'adm-%.6d.npy' % aid), res)
        
# p = Pool()
# p.map(copy_first_admissions, admission_ids)
# p.close()
# p.join()

**Comment by mengcz13** [comment]
Yes, this should be implemented in 9_getValidDataset.ipynb instead of here.
