### ISSUE TITLE
missing "mimiciii.mengcz_17features_first24h"

### ISSUE THREAD

**Issue by Luyaochen1** [USC-Melady/Benchmarking_DL_MIMICIII#2]
Hi, 

When I try to run "10_get_17-features-processed(fromdb).ipynb", the view/table mimiciii.mengcz_17features_first24h can not be found?

Did I miss something? 

Regards.
Luyao

**Comment by mengcz13** [comment]
Sorry that I forgot uploading sql codes for generating the view. I have uploaded it and updated the readme.

**Comment by Luyaochen1** [comment]
Thanks. 
gen_17features_first24h.sql is now working well.

But, I have problems of gen_17features_first48h.sql, I believe the subsequent view ( which I run from the mimic/concept/firstday) did not generate first 2 days data.

**Comment by mengcz13** [comment]
I guess you might be in doubt about line 12:
```
    and ce.charttime between ie.intime and ie.intime + interval '1' day
```
Well the data is actually still in first 1 day, but **only id related columns in this view are used**, which are **non-temporal features**. You can search in "10_get_17-features-processed(fromdb).ipynb" and verify that.

The names of these two sql code files are a bit confusing... Because we originally wanted to finish the data process inside the database with these two pieces of codes, but found it much faster to do that with Python and numpy (the main reason could be that I was not familiar with SQL...). So in the end we only extracted the time series and stored them to process locally.
