### ISSUE TITLE
11_get_time_series_sample_99plus-features-raw_24hrs.ipynb

### ISSUE THREAD

**Issue by mostafaalishahi** [USC-Melady/Benchmarking_DL_MIMICIII#4]
I tried many times running your code in order to extract data from mimic but at some point in notebook number 11 '11_get_time_series_sample_99plus-features-raw_24hrs.ipynb' i get some unexpected error 

`RuntimeError file size unexpectedly exceeded zip64 limit`

After that, I downgraded and changed the version of numpy from the one you mentioned and I faced another error: 
`struct.error: 'L' format requires 0 <= number <= 4294967295.`

could you please help running this code?

**Comment by PeterChe1990** [comment]
This is a known issue for numpy with `python>=3.6` when you try to `savez()` a large numpy array of objects. https://github.com/numpy/numpy/issues/10776

It has not been solved officially.
To bypass this issue before it is solved in future versions of numpy, you can try any one of the following:
1. Use `python<3.6`, or
2. Use othe ways such as `pickle.dump()` instead of `np.savez()`
3. Manually modify your numpy: replace `force_zip64 = val.nbytes >= 2**30` in `_savez()` method by `force_zip64 = True`
